export const citiesOfPakistan = [
  "Karachi",
  "Lahore",
  "Islamabad",
  "Rawalpindi",
  "Faisalabad",
  "Multan",
  "Hyderabad",
  "Peshawar",
  "Quetta",
  "Sialkot",
  "Gujranwala",
  "Bahawalpur",
  "Sukkur",
  "Mardan",
  "Abbottabad",
  "Jhelum",
  "Okara",
  "Sargodha",
  "Sheikhupura",
  "Mirpur Khas",
  "Rahim Yar Khan",
];
